dusk-network/schnorr

.github/workflows/dusk_ci.yaml, src/error.rs, src/key_variants/double_key.rs, src/key_variants/single_key.rs, tests/double_key_tests.rs, tests/single_key_tests.rs
=> Compile lib structures in `no_std` env

.github/workflows/dusk_ci.yaml, Cargo.toml, src/key_variants/double_key.rs, src/key_variants/single_key.rs
=> Canon derive

Cargo.toml, src/gadgets.rs
=> Poseidon upgrade to v0.17.0

CHANGELOG.md, Cargo.toml
=> Impl #27 - Upgrade `dusk-pki` to `v0.5.3`

CHANGELOG.md, Cargo.toml, src/gadgets.rs, src/key_variants/double_key.rs, src/key_variants/single_key.rs
=> Update `dusk-poseidon` to `v0.18`

CHANGELOG.md, Cargo.toml
=> Pull dusk_pki from crates.io

CHANGELOG.md, Cargo.toml, tests/zk.rs
`dusk-plonk` related dependencies should be updated as well, such as
`poseidon252`
Resolves #37
=> Update `dusk-plonk` from `0.6` to `0.7`

Cargo.toml, README.md
=> Add missing sections to Cargo.toml

CHANGELOG.md, Cargo.toml, tests/zk.rs
=> Add default-features=false for rand_core 

Cargo.toml, src/key_variants.rs, src/key_variants/double_key.rs, src/key_variants/single_key.rs, tests/zk.rs
- Replace `sponge::hash` with `truncated::hash`
- Remove `truncate_bls_to_jubjub`
- Fix minor nits
Resolves: #56
=> Release 0.7.1

CHANGELOG.md, Cargo.toml
=> Release 0.8

.github/workflows/dusk_ci.yaml, CHANGELOG.md, Cargo.toml, rust-toolchain, src/gadgets.rs, src/key_variants/double_key.rs, src/key_variants/single_key.rs, src/lib.rs, tests/double_key.rs, tests/single_key.rs, tests/zk.rs
=> Update to `dusk-plonk` 0.9

CHANGELOG.md, Cargo.toml, src/key_variants/double_key.rs, src/key_variants/single_key.rs, tests/zk.rs
=> Add `rkyv` implementations behind feature

CHANGELOG.md, src/gadgets.rs, src/key_variants.rs, src/key_variants/double_key.rs, src/key_variants/single_key.rs, src/lib.rs
=> Add more documentation

CHANGELOG.md, benches/schnorr.rs, src/key_variants/double_key.rs, src/lib.rs, tests/double_key.rs, tests/zk.rs
=> Differentiate key variants

CHANGELOG.md, Cargo.toml, benches/schnorr.rs, src/key_variants/double_key.rs, src/key_variants/single_key.rs, src/keys.rs, src/keys/public.rs, src/keys/secret.rs, src/lib.rs, tests/double_key.rs, tests/keys.rs, tests/single_key.rs, tests/zk.rs
resolves #80
SecretKey got renamed to NoteSecretKey
PublicKey got renamed to NotePublicKey
=> Move secret/public key from dusk_pki into schnorr

CHANGELOG.md, Cargo.toml, src/key_variants/double_key.rs, src/key_variants/single_key.rs, src/keys/secret.rs, src/lib.rs, tests/double_key.rs, tests/single_key.rs, tests/zk.rs
Most notably: The signature creation is now a method of `NoteSecretKey`
Resolves: #81
=> Align crate structure to dusk-bls-sign

.github/workflows/dusk_ci.yaml, CHANGELOG.md, Cargo.toml, benches/schnorr.rs, src/gadgets.rs, tests/zk.rs
=> Update benchmarks to latest version of plonk

CHANGELOG.md, benches/schnorr.rs, src/signatures/double_key.rs, src/signatures/single_key.rs, tests/zk.rs
=> Rename `to_witness` to `append`

CHANGELOG.md, src/keys/public.rs, src/keys/secret.rs, src/lib.rs, src/signatures/double_key.rs, tests/double_key.rs
=> Remove `PublicKeyPair` from `DoubleSignature`

CHANGELOG.md, src/keys/public.rs
=> Change NotePublicKeyPair

CHANGELOG.md, README.md, src/keys/public.rs, src/keys/secret.rs, src/signatures.rs, tests/schnorr.rs, tests/schnorr_double.rs, tests/schnorr_var_generator.rs
=> Change `verify` to be a method on the public key
